/**
 * The curated icon set a workflow may declare. Names are lucide icon names;
 * the dashboard maps each to its glyph and falls back to the tier glyph for
 * anything else. Declare in code as `icon: WORKFLOW_ICONS.PRINTER`.
 */
export const WORKFLOW_ICONS = {
  ACTIVITY: 'Activity',
  ALERT: 'AlertTriangle',
  ARCHIVE: 'Archive',
  AWARD: 'Award',
  BARCODE: 'Barcode',
  BELL: 'Bell',
  BOT: 'Bot',
  BOX: 'Box',
  BOXES: 'Boxes',
  BUILDING: 'Building2',
  CALENDAR: 'Calendar',
  CAMERA: 'Camera',
  CHECKLIST: 'ListChecks',
  CLIPBOARD: 'ClipboardList',
  CLIPBOARD_CHECK: 'ClipboardCheck',
  CLOCK: 'Clock',
  COG: 'Cog',
  CPU: 'Cpu',
  DATABASE: 'Database',
  DOWNLOAD: 'Download',
  DROPLETS: 'Droplets',
  FACTORY: 'Factory',
  FAN: 'Fan',
  FILE: 'FileText',
  FLAG: 'Flag',
  FLAME: 'Flame',
  GAUGE: 'Gauge',
  HAMMER: 'Hammer',
  HEART: 'Heart',
  IMAGE: 'Image',
  KEY: 'Key',
  LAYERS: 'Layers',
  LEAF: 'Leaf',
  LIFEBUOY: 'LifeBuoy',
  LOCK: 'Lock',
  MAIL: 'Mail',
  MAP: 'Map',
  MEGAPHONE: 'Megaphone',
  MESSAGE: 'MessageSquare',
  PACKAGE: 'Package',
  PALETTE: 'Palette',
  PEN: 'PenTool',
  PILL: 'Pill',
  POWER: 'Power',
  PRINTER: 'Printer',
  RECEIPT: 'Receipt',
  RECYCLE: 'Recycle',
  REFRESH: 'RefreshCw',
  ROCKET: 'Rocket',
  ROUTE: 'Route',
  RULER: 'Ruler',
  SCALE: 'Scale',
  SCAN: 'ScanBarcode',
  SCISSORS: 'Scissors',
  SEARCH: 'Search',
  SEND: 'Send',
  SERVER: 'Server',
  SHIELD: 'ShieldCheck',
  SHOPPING_CART: 'ShoppingCart',
  SNOWFLAKE: 'Snowflake',
  SPARKLES: 'Sparkles',
  STAR: 'Star',
  STORE: 'Store',
  SUN: 'Sun',
  TAG: 'Tag',
  TEST_TUBE: 'TestTube',
  THERMOMETER: 'Thermometer',
  TRASH: 'Trash2',
  TRUCK: 'Truck',
  UPLOAD: 'Upload',
  USER: 'User',
  USERS: 'Users',
  WAND: 'Wand2',
  WAREHOUSE: 'Warehouse',
  WIFI: 'Wifi',
  WRENCH: 'Wrench',
  ZAP: 'Zap',
} as const;

export type WorkflowIconName = (typeof WORKFLOW_ICONS)[keyof typeof WORKFLOW_ICONS];

const NAMES = new Set<string>(Object.values(WORKFLOW_ICONS));

export function isWorkflowIcon(value: unknown): value is WorkflowIconName {
  return typeof value === 'string' && NAMES.has(value);
}
