// ── Admin tool manifests ─────────────────────────────────────────────────────
// Each entry mirrors the exact tool registered in system/mcp-servers/admin/

export const ADMIN_TOOLS = [
  // ── tasks.ts ────────────────────────────────────────────────────────────
  { name: 'find_tasks', description: 'Search tasks with optional filters. Returns task records with workflow_id, status, workflow_type, and timestamps.', read_safe: true, inputSchema: { type: 'object', properties: { status: { type: 'string' }, workflow_type: { type: 'string' }, workflow_id: { type: 'string' }, origin_id: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'get_process_detail', description: 'Get all tasks and escalations for a process (origin_id).', read_safe: true, inputSchema: { type: 'object', properties: { origin_id: { type: 'string' } }, required: ['origin_id'] } },

  // ── escalations.ts ──────────────────────────────────────────────────────
  { name: 'find_escalations', description: 'Search escalations with optional filters (status, role, type, subtype, assigned_to, priority), free-text search (description + metadata values, e.g. a correlation key), and sorting. Returns full records including metadata.', read_safe: true, inputSchema: { type: 'object', properties: { status: { type: 'string', enum: ['pending', 'resolved', 'cancelled', 'expired'] }, role: { type: 'string' }, type: { type: 'string' }, subtype: { type: 'string' }, assigned_to: { type: 'string' }, search: { type: 'string' }, priority: { type: 'integer' }, sort_by: { type: 'string', enum: ['created_at', 'priority', 'updated_at'] }, order: { type: 'string', enum: ['asc', 'desc'] }, limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'get_escalation', description: 'Get a single escalation by ID — the full record including metadata, payloads, signal_key, and assignment state.', read_safe: true, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'get_escalations_by_workflow', description: 'List all escalations linked to a workflow ID, newest first. Returns full records including metadata.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' } }, required: ['workflow_id'] } },
  { name: 'get_escalation_stats', description: 'Aggregated escalation statistics: pending, claimed, created, resolved counts with breakdown by role.', read_safe: true, inputSchema: { type: 'object', properties: { period: { type: 'string' } } } },
  { name: 'claim_escalation', description: 'Claim an escalation for a time-boxed lock.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, duration_minutes: { type: 'integer' } }, required: ['id'] } },
  { name: 'release_escalation', description: 'Release a claimed escalation back to the available pool.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'resolve_escalation', description: 'Resolve a pending escalation with a human-provided payload. Efficient escalations resume the waiting workflow in place; legacy paths signal or re-run.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, resolverPayload: { type: 'object' } }, required: ['id', 'resolverPayload'] } },
  { name: 'resolve_by_signal_key', description: 'Resolve an efficient (atomic) escalation directly by its signal_key and resume the waiting workflow in place.', read_safe: false, inputSchema: { type: 'object', properties: { signalKey: { type: 'string' }, resolverPayload: { type: 'object' } }, required: ['signalKey', 'resolverPayload'] } },
  { name: 'escalate_escalation', description: 'Route a pending escalation to a different role per the escalation chain.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, targetRole: { type: 'string' } }, required: ['id', 'targetRole'] } },
  { name: 'cancel_escalation', description: 'Permanently cancel a pending escalation (e.g. its workflow has terminated). Preserved for audit.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'bulk_cancel', description: 'Cancel multiple pending escalations in a single operation.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } } }, required: ['ids'] } },
  { name: 'release_expired_claims', description: 'Release all escalation claims that exceeded their lock duration.', read_safe: false, inputSchema: { type: 'object', properties: {} } },
  { name: 'bulk_triage', description: 'Resolve escalations for triage and start mcpTriage workflows.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } }, hint: { type: 'string' } }, required: ['ids'] } },
  { name: 'resolve_by_ids', description: 'Resolve a set of escalations by id in one guarded statement, RBAC-scoped to the caller\'s roles.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } }, resolverPayload: { type: 'object' }, metadata: { type: 'object' } }, required: ['ids', 'resolverPayload'] } },
  { name: 'search_by_facets', description: 'Faceted search over a pond, scoped to the caller\'s role: status, availability, metadata facets, sorting, and paging.', read_safe: true, inputSchema: { type: 'object', properties: { role: { type: 'string' }, status: { type: 'string' }, available: { type: 'boolean' }, facets: { type: 'object' }, orderBy: { type: 'array' }, limit: { type: 'integer' }, offset: { type: 'integer' } }, required: ['role'] } },
  { name: 'claim_groups', description: 'Batch-claim complete origin groups (orders) in priority order over a pond, assigned to the calling principal.', read_safe: false, inputSchema: { type: 'object', properties: { query: { type: 'object' }, limit: { type: 'integer' }, durationMinutes: { type: 'integer' }, sizeFacet: { type: 'string' } }, required: ['query'] } },
  { name: 'claim_by_facets', description: 'Batch-claim individual rows matching a facet query, assigned to the calling principal. With allOrNone, commits only the full set.', read_safe: false, inputSchema: { type: 'object', properties: { query: { type: 'object' }, limit: { type: 'integer' }, durationMinutes: { type: 'integer' }, allOrNone: { type: 'boolean' } }, required: ['query'] } },
  { name: 'aggregate_by_facets', description: 'Grouped analytics over the escalation intervals: membership (rows or distinct entities open at an instant, incl. past instants) or dwell (open-seconds per group within a window), grouped by role/subtype/status columns, metadata facet keys, or the derived entity STATE (query.entity + groupBy.state answers "how do the entities spend their time").', read_safe: true, inputSchema: { type: 'object', properties: { query: { type: 'object' }, groupBy: { type: 'object' }, measure: { type: 'object' }, distinctBy: { type: 'string' }, states: { type: 'array' }, liveStatuses: { type: 'array', items: { type: 'string' } }, orderBy: { type: 'array' }, limit: { type: 'integer' }, offset: { type: 'integer' } }, required: ['query', 'groupBy', 'measure'] } },
  { name: 'timeline_by_facet', description: 'One entity\'s ordered escalation-interval timeline: [startedAt, endedAt) spans with durations in created_at order; open intervals report endedAt null; gaps are untracked time and are preserved.', read_safe: true, inputSchema: { type: 'object', properties: { facet: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' } }, required: ['key', 'value'] }, query: { type: 'object' }, window: { type: 'object' }, select: { type: 'object' }, liveStatuses: { type: 'array', items: { type: 'string' } }, limit: { type: 'integer' } }, required: ['facet'] } },
  { name: 'find_by_metadata', description: 'Find escalations by a metadata key-value pair.', read_safe: true, inputSchema: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' }, status: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' } }, required: ['key', 'value'] } },
  { name: 'claim_by_metadata', description: 'Find and claim an escalation by metadata key-value pair. Supports provisionIfAbsent for JIT user+role provisioning (superadmin only).', read_safe: false, inputSchema: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' }, durationMinutes: { type: 'integer' }, assignee: { type: 'string' }, metadata: { type: 'object' }, provisionIfAbsent: { type: 'object', description: 'JIT-provision assignee if absent: { displayName?, email?, roles?: [{ role, type? }] }' } }, required: ['key', 'value'] } },
  { name: 'resolve_by_metadata', description: 'Find and resolve an escalation by metadata key-value pair. Signal-backed escalations (metadata.signal_id) are signaled to the workflow instead of resolved directly.', read_safe: false, inputSchema: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' }, resolverPayload: { type: 'object' }, assignee: { type: 'string' }, metadata: { type: 'object' } }, required: ['key', 'value', 'resolverPayload'] } },
  { name: 'bulk_claim', description: 'Claim multiple escalations in a single operation.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } }, durationMinutes: { type: 'integer' } }, required: ['ids'] } },
  { name: 'bulk_assign', description: 'Assign multiple escalations to a specific user. Rows under a live claim are skipped (counted in skipped) unless reassign=true — the admin takeover, which hands live-claimed rows to the target atomically.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } }, targetUserId: { type: 'string' }, durationMinutes: { type: 'integer' }, reassign: { type: 'boolean' } }, required: ['ids', 'targetUserId'] } },
  { name: 'bulk_unassign', description: 'Return claimed escalations to the available pool — the admin override of a live claim (self-return stays the release verb). Unclaimed and terminal rows are skipped.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } } }, required: ['ids'] } },
  { name: 'bulk_escalate', description: 'Escalate multiple escalations to a different role.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } }, targetRole: { type: 'string' } }, required: ['ids', 'targetRole'] } },
  { name: 'update_priority', description: 'Update the priority of multiple escalations.', read_safe: false, inputSchema: { type: 'object', properties: { ids: { type: 'array', items: { type: 'string' } }, priority: { type: 'integer' } }, required: ['ids', 'priority'] } },

  // ── workflow-config.ts ──────────────────────────────────────────────────
  { name: 'list_workflow_configs', description: 'List all certified workflow configurations with roles and settings.', read_safe: true, inputSchema: { type: 'object', properties: {} } },
  { name: 'upsert_workflow_config', description: 'Create or replace a workflow configuration (certify). Activates the interceptor for task tracking and escalation chains.', read_safe: false, inputSchema: { type: 'object', properties: { workflow_type: { type: 'string' }, invocable: { type: 'boolean' }, task_queue: { type: 'string' }, default_role: { type: 'string' }, description: { type: 'string' }, execute_as: { type: 'string' }, roles: { type: 'array', items: { type: 'string' } }, invocation_roles: { type: 'array', items: { type: 'string' } }, consumes: { type: 'array', items: { type: 'string' } }, tool_tags: { type: 'array', items: { type: 'string' } }, cron_schedule: { type: 'string' } }, required: ['workflow_type'] } },
  { name: 'delete_workflow_config', description: 'De-certify a workflow by removing its config entry.', read_safe: false, inputSchema: { type: 'object', properties: { workflow_type: { type: 'string' } }, required: ['workflow_type'] } },

  // ── workflows.ts ────────────────────────────────────────────────────────
  { name: 'list_discovered_workflows', description: 'Unified list of all known workflows: active workers, historical entities, and registered configs.', read_safe: true, inputSchema: { type: 'object', properties: { include_system: { type: 'boolean' } } } },
  { name: 'invoke_workflow', description: 'Start a certified workflow by type. Returns workflow ID immediately. options passes HotMesh WorkflowOptions through (workflowId for deterministic ids per the deployment\'s id convention; entity/expire/search are safe; taskQueue/namespace reroute execution — set only deliberately).', read_safe: false, inputSchema: { type: 'object', properties: { workflow_type: { type: 'string' }, data: { type: 'object' }, metadata: { type: 'object' }, execute_as: { type: 'string' }, options: { type: 'object' } }, required: ['workflow_type', 'data'] } },
  { name: 'invoke_workflow_read_safe', description: 'Start a workflow registered read-safe (side-effect-free). Same contract as invoke_workflow, gated to configs carrying read_safe=true — any workflow may be attempted; one lacking the flag fails with a clear error. The invocation surface for read-scoped callers.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_type: { type: 'string' }, data: { type: 'object' }, metadata: { type: 'object' }, execute_as: { type: 'string' }, options: { type: 'object' } }, required: ['workflow_type', 'data'] } },
  { name: 'get_workflow_status', description: 'Check workflow status and result. Returns status (running | complete) and result if complete. Namespace-aware — pass app_id to read a workflow running in a non-default HotMesh namespace.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' }, app_id: { type: 'string' } }, required: ['workflow_id'] } },
  { name: 'terminate_workflow', description: 'Completely terminate a workflow: kills the durable handle AND cancels its pending escalations. The correct way to stop a workflow — prefer over interrupt_pipeline_job, which strands escalations as orphans.', read_safe: false, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' } }, required: ['workflow_id'] } },

  // ── mcp-servers.ts ──────────────────────────────────────────────────────
  { name: 'list_mcp_servers', description: 'List registered MCP servers with optional filters by status, tags, or search.', read_safe: true, inputSchema: { type: 'object', properties: { status: { type: 'string' }, tags: { type: 'string' }, search: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'update_mcp_server', description: 'Update an MCP server registration (tags, description, auto_connect).', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, auto_connect: { type: 'boolean' } }, required: ['id'] } },
  { name: 'connect_mcp_server', description: 'Connect to a registered MCP server.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'disconnect_mcp_server', description: 'Disconnect from an MCP server.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },

  // ── yaml-workflows.ts ───────────────────────────────────────────────────
  { name: 'list_yaml_workflows', description: 'List compiled YAML workflows with optional status, namespace, or search filter.', read_safe: true, inputSchema: { type: 'object', properties: { status: { type: 'string' }, app_id: { type: 'string' }, search: { type: 'string' }, source_workflow_id: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'get_yaml_workflow', description: 'Inspect a compiled workflow by ID. Returns activity manifest, schemas, and YAML content.', read_safe: true, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'create_yaml_workflow', description: 'Compile a completed execution into a deterministic YAML workflow. Stored as a draft.', read_safe: false, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' }, task_queue: { type: 'string' }, workflow_name: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' }, app_id: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, compilation_feedback: { type: 'string' } }, required: ['workflow_id', 'task_queue', 'workflow_name', 'name'] } },
  { name: 'deploy_yaml_workflow', description: 'Deploy a compiled YAML workflow, activate it, and register workers.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'invoke_yaml_workflow', description: 'Run a compiled YAML workflow. Deterministic — no LLM. Set sync=true to wait.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, data: { type: 'object' }, sync: { type: 'boolean' }, timeout: { type: 'integer' } }, required: ['id'] } },

  // ── users.ts (users + roles) ────────────────────────────────────────────
  { name: 'list_users', description: 'List user accounts with optional role and status filters.', read_safe: true, inputSchema: { type: 'object', properties: { role: { type: 'string' }, status: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'create_user', description: 'Create a new user account with optional roles.', read_safe: false, inputSchema: { type: 'object', properties: { external_id: { type: 'string' }, display_name: { type: 'string' }, email: { type: 'string' }, roles: { type: 'array', items: { type: 'object', properties: { role: { type: 'string' }, type: { type: 'string', enum: ['superadmin', 'admin', 'member'] } }, required: ['role', 'type'] } } }, required: ['external_id'] } },
  { name: 'add_user_role', description: 'Assign a role to a user.', read_safe: false, inputSchema: { type: 'object', properties: { user_id: { type: 'string' }, role: { type: 'string' }, type: { type: 'string', enum: ['superadmin', 'admin', 'member'] } }, required: ['user_id', 'role', 'type'] } },
  { name: 'remove_user_role', description: 'Remove a role from a user.', read_safe: false, inputSchema: { type: 'object', properties: { user_id: { type: 'string' }, role: { type: 'string' } }, required: ['user_id', 'role'] } },
  { name: 'patch_user_properties', description: 'Atomically patch a user\'s properties dictionary — set/remove/rename keys in one statement, never read-merge-write; identity-binding keys assert uniqueness among active users.', read_safe: false, inputSchema: { type: 'object', properties: { user_id: { type: 'string' }, set: { type: 'object' }, remove: { type: 'array', items: { type: 'string' } }, rename: { type: 'object' } }, required: ['user_id'] } },
  { name: 'list_roles', description: 'List all distinct roles known to the system.', read_safe: true, inputSchema: { type: 'object', properties: {} } },
  { name: 'create_role', description: 'Create a new role. Lowercase alphanumeric with hyphens/underscores.', read_safe: false, inputSchema: { type: 'object', properties: { role: { type: 'string' } }, required: ['role'] } },
  { name: 'add_escalation_chain', description: 'Define an escalation path from one role to another.', read_safe: false, inputSchema: { type: 'object', properties: { source_role: { type: 'string' }, target_role: { type: 'string' } }, required: ['source_role', 'target_role'] } },
  { name: 'update_role', description: 'Update role metadata with PATCH semantics (omitted fields keep their values): display name, description, form/metadata/list schemas, properties bag, ops_visible flag, parent role, default_pins (member pinned-view seeds), and the typed operational targets. A schema change snapshots the pair into the version history.', read_safe: false, inputSchema: { type: 'object', properties: { role: { type: 'string' }, title: { type: 'string' }, description: { type: 'string' }, form_schema: { type: 'object' }, metadata_schema: { type: 'object' }, properties: { type: 'object' }, ops_visible: { type: 'boolean' }, ops_home_default: { type: 'boolean' }, parent_role: { type: 'string' }, sla_minutes: { type: 'number' }, target_per_hour: { type: 'number' }, worker_count: { type: 'integer' }, priority_threshold_minutes: { type: 'number' }, priority_facet: { type: 'string' }, entity_facet: { type: 'string' }, entity_state_source: { type: 'string', enum: ['role', 'subtype'] }, upstream_roles: { type: 'array', items: { type: 'string' } }, list_schema: { type: 'object' }, default_pins: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, url: { type: 'string' }, badge: { type: 'boolean' } }, required: ['label', 'url'] } }, change_summary: { type: 'string' } }, required: ['role'] } },
  { name: 'get_role_schema', description: 'Fetch a role\'s form_schema + metadata_schema pair — the live (latest) schema, or an immutable snapshot when a version is given (the version escalations pin via metadata.schema_version).', read_safe: true, inputSchema: { type: 'object', properties: { role: { type: 'string' }, version: { type: 'integer' } }, required: ['role'] } },
  { name: 'list_role_schema_versions', description: 'List a role\'s schema version history, newest first. Each schema edit creates a new version; fetch a full snapshot with get_role_schema.', read_safe: true, inputSchema: { type: 'object', properties: { role: { type: 'string' } }, required: ['role'] } },

  // ── personas.ts ─────────────────────────────────────────────────────────
  { name: 'list_personas', description: 'List all personas — named role bundles with per-role relationship scope — with role links and holder counts.', read_safe: true, inputSchema: { type: 'object', properties: {} } },
  { name: 'get_persona', description: 'Fetch one persona with its role links and current assignees.', read_safe: true, inputSchema: { type: 'object', properties: { key: { type: 'string' } }, required: ['key'] } },
  { name: 'create_persona', description: 'Create a persona (a named role bundle). Link roles with link_persona_role, then assign users with assign_persona.', read_safe: false, inputSchema: { type: 'object', properties: { key: { type: 'string' }, title: { type: 'string' }, description: { type: 'string' } }, required: ['key'] } },
  { name: 'update_persona', description: 'Update a persona\'s title/description with PATCH semantics (null clears).', read_safe: false, inputSchema: { type: 'object', properties: { key: { type: 'string' }, title: { type: 'string' }, description: { type: 'string' } }, required: ['key'] } },
  { name: 'delete_persona', description: 'Delete a persona. Memberships it sustains are removed or re-homed to a sibling persona; direct grants are never touched.', read_safe: false, inputSchema: { type: 'object', properties: { key: { type: 'string' } }, required: ['key'] } },
  { name: 'link_persona_role', description: 'Link a role to a persona at a relationship scope (write-all = full worker, write-self = own assignments only, read-all = observer), or change an existing link. Reconciles every holder\'s memberships.', read_safe: false, inputSchema: { type: 'object', properties: { key: { type: 'string' }, role: { type: 'string' }, relationship: { type: 'string', enum: ['write-all', 'write-self', 'read-all', 'write-none'] } }, required: ['key', 'role', 'relationship'] } },
  { name: 'unlink_persona_role', description: 'Remove a role link from a persona and reconcile every holder\'s memberships.', read_safe: false, inputSchema: { type: 'object', properties: { key: { type: 'string' }, role: { type: 'string' } }, required: ['key', 'role'] } },
  { name: 'assign_persona', description: 'Assign a persona to a user — shorthand for adding the user to each linked role at the linked scope. Idempotent: re-assigning overlays fresh. Highest allowance wins across bundles; direct grants only ever raised.', read_safe: false, inputSchema: { type: 'object', properties: { user_id: { type: 'string' }, key: { type: 'string' } }, required: ['user_id', 'key'] } },
  { name: 'unassign_persona', description: 'Unassign a persona from a user, removing only the memberships it sustains (rows a sibling persona still grants are re-homed; direct grants untouched).', read_safe: false, inputSchema: { type: 'object', properties: { user_id: { type: 'string' }, key: { type: 'string' } }, required: ['user_id', 'key'] } },
  { name: 'get_user_personas', description: 'The personas a user holds plus the composed role/scope map their memberships form (each row names its sustaining persona, or null for a direct grant).', read_safe: true, inputSchema: { type: 'object', properties: { user_id: { type: 'string' } }, required: ['user_id'] } },

  { name: 'diagnose_job', description: 'Read-only diagnosis for a single workflow job: status, idle time, stream summary, escalation row, and structured findings with evidence.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' }, app_id: { type: 'string' }, max_events: { type: 'integer' }, include: { type: 'array', items: { type: 'string', enum: ['events', 'streams'] } }, verbosity: { type: 'string', enum: ['summary', 'full'] } }, required: ['workflow_id'] } },
  { name: 'find_stalled_jobs', description: 'List workflow jobs idle beyond a threshold, each classified as healthy-wait or likely-fault.', read_safe: true, inputSchema: { type: 'object', properties: { app_id: { type: 'string' }, idle_minutes: { type: 'integer' }, workflow_type: { type: 'string' }, limit: { type: 'integer' } } } },
  { name: 'find_orphaned_signals', description: 'Scan recent worker streams for signals whose waiting workflow is gone.', read_safe: true, inputSchema: { type: 'object', properties: { app_id: { type: 'string' }, within_hours: { type: 'integer' }, limit: { type: 'integer' } } } },

  // ── maintenance.ts ──────────────────────────────────────────────────────
  { name: 'prune', description: 'Prune expired jobs, streams, and execution artifacts from the database.', read_safe: false, inputSchema: { type: 'object', properties: { expire: { type: 'string' }, jobs: { type: 'boolean' }, streams: { type: 'boolean' }, entities: { type: 'array', items: { type: 'string' } }, prune_transient: { type: 'boolean' } } } },

  // ── agents.ts ───────────────────────────────────────────────────────────
  { name: 'list_agents', description: 'List agent automations with optional status and knowledge domain filters.', read_safe: true, inputSchema: { type: 'object', properties: { status: { type: 'string' }, knowledge_domain: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'get_agent', description: 'Get a single agent automation by ID with aggregated stats.', read_safe: true, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'create_agent', description: 'Create a new agent automation with identity, goals, rules, and subscriptions.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, description: { type: 'string' }, goals: { type: 'array', items: { type: 'string' } }, rules: { type: 'array', items: { type: 'string' } }, status: { type: 'string' }, knowledge_domain: { type: 'string' }, schedules: { type: 'array' }, subscriptions: { type: 'array' } }, required: ['id'] } },
  { name: 'update_agent', description: 'Update an existing agent automation.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, description: { type: 'string' }, goals: { type: 'array', items: { type: 'string' } }, rules: { type: 'array', items: { type: 'string' } }, status: { type: 'string' }, knowledge_domain: { type: 'string' } }, required: ['id'] } },
  { name: 'delete_agent', description: 'Delete an agent automation and all its subscriptions.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },

  // ── agent-subscriptions.ts ──────────────────────────────────────────────
  { name: 'list_agent_subscriptions', description: 'List all event subscriptions for an agent.', read_safe: true, inputSchema: { type: 'object', properties: { agent_id: { type: 'string' } }, required: ['agent_id'] } },
  { name: 'create_agent_subscription', description: 'Create an event subscription for an agent.', read_safe: false, inputSchema: { type: 'object', properties: { agent_id: { type: 'string' }, topic: { type: 'string' }, reaction_type: { type: 'string' }, workflow_type: { type: 'string' }, pipeline_id: { type: 'string' }, mcp_prompt: { type: 'string' }, input_mapping: { type: 'object' }, filter: { type: 'object' }, execute_as: { type: 'string' } }, required: ['agent_id', 'topic', 'reaction_type'] } },
  { name: 'delete_agent_subscription', description: 'Delete an event subscription by ID.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },

  // ── bot-accounts.ts ─────────────────────────────────────────────────────
  { name: 'list_bot_accounts', description: 'List all bot (service) accounts with pagination.', read_safe: true, inputSchema: { type: 'object', properties: { limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'get_bot_account', description: 'Get a single bot account by ID.', read_safe: true, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'create_bot_account', description: 'Create a new bot (service) account with optional roles.', read_safe: false, inputSchema: { type: 'object', properties: { name: { type: 'string' }, description: { type: 'string' }, display_name: { type: 'string' }, roles: { type: 'array', items: { type: 'object', properties: { role: { type: 'string' }, type: { type: 'string' } } } } }, required: ['name'] } },
  { name: 'update_bot_account', description: 'Update a bot account (display name, description, status).', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, display_name: { type: 'string' }, description: { type: 'string' }, status: { type: 'string' } }, required: ['id'] } },
  { name: 'delete_bot_account', description: 'Delete a bot account and all its API keys.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'create_bot_api_key', description: 'Generate a new API key for a bot account. Returns the raw key ONCE.', read_safe: false, inputSchema: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, scopes: { type: 'array', items: { type: 'string' } }, expires_at: { type: 'string' } }, required: ['id', 'name'] } },
  { name: 'revoke_bot_api_key', description: 'Revoke (delete) an API key for a bot account.', read_safe: false, inputSchema: { type: 'object', properties: { key_id: { type: 'string' } }, required: ['key_id'] } },

  // ── controlplane.ts ─────────────────────────────────────────────────────
  { name: 'list_apps', description: 'List available HotMesh application namespaces.', read_safe: true, inputSchema: { type: 'object', properties: {} } },
  { name: 'rollcall', description: 'Execute a roll call — discovers all engines and workers in the mesh.', read_safe: true, inputSchema: { type: 'object', properties: { app_id: { type: 'string' }, delay: { type: 'integer' } } } },
  { name: 'apply_throttle', description: 'Apply a throttle to the mesh (-1=pause, 0=resume, >0=delay ms per message).', read_safe: false, inputSchema: { type: 'object', properties: { appId: { type: 'string' }, throttle: { type: 'integer' }, topic: { type: 'string' }, guid: { type: 'string' }, scope: { type: 'string' } }, required: ['throttle'] } },
  { name: 'get_stream_stats', description: 'Stream processing statistics — pending count and processed volume by time range.', read_safe: true, inputSchema: { type: 'object', properties: { app_id: { type: 'string' }, duration: { type: 'string' }, stream: { type: 'string' } } } },
  { name: 'list_stream_messages', description: 'Browse stream messages with pagination, filtering, and sorting.', read_safe: true, inputSchema: { type: 'object', properties: { namespace: { type: 'string' }, source: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' }, sort_by: { type: 'string' }, order: { type: 'string', enum: ['asc', 'desc'] }, status: { type: 'string' }, stream_name: { type: 'string' }, msg_type: { type: 'string' }, topic: { type: 'string' }, workflow_name: { type: 'string' }, jid: { type: 'string' }, aid: { type: 'string' } }, required: ['namespace', 'source'] } },

  // ── pipelines.ts ────────────────────────────────────────────────────────
  { name: 'list_pipeline_entities', description: 'List distinct entity (tool) names from pipeline jobs.', read_safe: true, inputSchema: { type: 'object', properties: { app_id: { type: 'string' } } } },
  { name: 'list_pipeline_jobs', description: 'List pipeline jobs with optional entity, search, and status filters.', read_safe: true, inputSchema: { type: 'object', properties: { app_id: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' }, entity: { type: 'string' }, search: { type: 'string' }, status: { type: 'string' }, sort_by: { type: 'string' }, order: { type: 'string', enum: ['asc', 'desc'] } } } },
  { name: 'get_pipeline_execution', description: 'Export execution details for a specific pipeline job. Histories run large — pass select (dot paths) to return only what you need.', read_safe: true, inputSchema: { type: 'object', properties: { job_id: { type: 'string' }, app_id: { type: 'string' }, select: { type: 'array', items: { type: 'string' } } }, required: ['job_id'] } },
  { name: 'interrupt_pipeline_job', description: 'Engine-level interrupt of a running job. WARNING: does NOT cancel the workflow\'s escalations — they are stranded as pending orphans. Prefer terminate_workflow to stop a workflow cleanly; use this only for a raw engine interrupt.', read_safe: false, inputSchema: { type: 'object', properties: { job_id: { type: 'string' }, topic: { type: 'string' }, app_id: { type: 'string' } }, required: ['job_id', 'topic'] } },

  // ── topics.ts ───────────────────────────────────────────────────────────
  { name: 'list_topics', description: 'List topics in the event catalog with optional category and search filters.', read_safe: true, inputSchema: { type: 'object', properties: { category: { type: 'string' }, search: { type: 'string' }, limit: { type: 'integer' }, offset: { type: 'integer' } } } },
  { name: 'get_topic', description: 'Get a single topic by name, including schema and example payload.', read_safe: true, inputSchema: { type: 'object', properties: { topic: { type: 'string' } }, required: ['topic'] } },
  { name: 'create_topic', description: 'Register a new topic in the event catalog.', read_safe: false, inputSchema: { type: 'object', properties: { topic: { type: 'string' }, category: { type: 'string' }, description: { type: 'string' }, payload_schema: { type: 'object' }, example_payload: { type: 'object' }, tags: { type: 'array', items: { type: 'string' } } }, required: ['topic', 'category'] } },
  { name: 'update_topic', description: 'Update a topic in the event catalog.', read_safe: false, inputSchema: { type: 'object', properties: { topic: { type: 'string' }, description: { type: 'string' }, category: { type: 'string' }, payload_schema: { type: 'object' }, example_payload: { type: 'object' }, tags: { type: 'array', items: { type: 'string' } } }, required: ['topic'] } },
  { name: 'delete_topic', description: 'Delete a topic from the catalog (system topics are protected).', read_safe: false, inputSchema: { type: 'object', properties: { topic: { type: 'string' } }, required: ['topic'] } },

  // ── settings.ts ─────────────────────────────────────────────────────────
  { name: 'get_settings', description: 'Get frontend-relevant configuration (no secrets). Returns feature flags, enabled capabilities, and system metadata.', read_safe: true, inputSchema: { type: 'object', properties: {} } },

  // ── exports.ts ──────────────────────────────────────────────────────────
  { name: 'list_export_jobs', description: 'List workflow jobs with optional filtering and pagination.', read_safe: true, inputSchema: { type: 'object', properties: { limit: { type: 'integer' }, offset: { type: 'integer' }, entity: { type: 'string' }, search: { type: 'string' }, status: { type: 'string' }, sort_by: { type: 'string' }, order: { type: 'string', enum: ['asc', 'desc'] } } } },
  { name: 'export_workflow_state', description: 'Export the full workflow state using HotMesh durable export. allow/block filter which sections the engine fetches; select (dot paths) projects the returned JSON.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' }, allow: { type: 'array', items: { type: 'string' } }, block: { type: 'array', items: { type: 'string' } }, values: { type: 'object' }, select: { type: 'array', items: { type: 'string' } } }, required: ['workflow_id'] } },
  { name: 'export_workflow_execution', description: 'Export workflow state as a structured execution event history. Histories run large — pass select (dot paths) to return only what you need.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' }, excludeSystem: { type: 'boolean' }, omitResults: { type: 'boolean' }, mode: { type: 'string' }, maxDepth: { type: 'integer' }, select: { type: 'array', items: { type: 'string' } } }, required: ['workflow_id'] } },
  { name: 'get_workflow_envelopes', description: 'The workflow\'s input and output envelopes — two narrow lookups, no event stream. Output is null with status running until the workflow completes; a failed run carries its error message.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' } }, required: ['workflow_id'] } },
  { name: 'get_export_status', description: 'Return the numeric status semaphore for a workflow.', read_safe: true, inputSchema: { type: 'object', properties: { workflow_id: { type: 'string' } }, required: ['workflow_id'] } },

  // ── overview.ts ─────────────────────────────────────────────────────────
  { name: 'get_system_overview', description: 'Triage-ready system dashboard: escalation queue pressure, task throughput, hourly trends, infrastructure status, and process summary. One call for complete system state.', read_safe: true, inputSchema: { type: 'object', properties: { period: { type: 'string', enum: ['1h', '24h', '7d'], description: 'Time window (default: 24h)' } } } },

  // ── domain-context.ts ─────────────────────────────────────────────────────
  { name: 'get_domain_context', description: 'The deployment\'s domain dictionary merged with live platform state — how this operation\'s jargon maps to roles, workflows, escalations, and metadata facets. No args returns the overview + index; { topic, name } returns specific entries (entity id facet + roles for building escalation queries, role cancel/timeout semantics, workflow kill road); topic `term` looks a word or alias up across every kind. Works on every deployment — with no dictionary registered it serves a view derived from the live registries. Call before acting on deployment-specific semantics.', read_safe: true, inputSchema: { type: 'object', properties: { topic: { type: 'string', enum: ['term', 'entity', 'role', 'workflow', 'facet', 'action', 'rule', 'runbook'] }, name: { type: 'string' } } } },

  // ── scan-codes.ts ────────────────────────────────────────────────────────
  { name: 'execute_scan_code', description: 'Execute a raw scan code (version:category:target): parse against the configured schemes, walk the rule\'s condition/action steps, and return a structured outcome. Identity-kind schemes mint an acting-identity grant; with actingToken, mutating verbs attribute to the badged person.', read_safe: false, inputSchema: { type: 'object', properties: { code: { type: 'string' }, actingToken: { type: 'string' }, previousActingToken: { type: 'string' } }, required: ['code'] } },
  { name: 'execute_scan_choice', description: 'Execute one choice presented by a PRESENT step (the info-choice screen). The pointer is re-validated against live config, row state, the acting-identity gate, and RBAC before the verb runs.', read_safe: false, inputSchema: { type: 'object', properties: { schemeVersion: { type: 'integer' }, category: { type: 'string' }, stepIndex: { type: 'integer' }, choiceIndex: { type: 'integer' }, escalationId: { type: 'string' }, actingToken: { type: 'string' } }, required: ['schemeVersion', 'category', 'stepIndex', 'choiceIndex', 'escalationId'] } },
  { name: 'list_scan_schemes', description: 'List all scan-code schemes: version digit, name, target metadata facet, and encoding (fixed digits or delimited text).', read_safe: true, inputSchema: { type: 'object', properties: {} } },
  { name: 'upsert_scan_scheme', description: 'Create or replace a scan scheme: which metadata facet the scanned target resolves against and how the code string parses. kind=identity turns the scheme into a badge layer minting acting-identity grants.', read_safe: false, inputSchema: { type: 'object', properties: { version: { type: 'integer' }, name: { type: 'string' }, target_facet: { type: 'string' }, encoding: { type: 'string', enum: ['fixed', 'delimited'] }, delimiter: { type: 'string' }, target_length: { type: 'integer' }, kind: { type: 'string', enum: ['action', 'identity'] }, grant_ttl_seconds: { type: 'integer' }, grant_max_uses: { type: 'integer' }, enabled: { type: 'boolean' } }, required: ['version', 'name', 'target_facet'] } },
  { name: 'upsert_scan_rule', description: 'Create or replace a scan rule for a scheme category: friendly name, ordered condition/action steps (first matching query wins), a no-match fallback screen, and a not-primed screen for identity-required steps. present-verb steps carry a labeled choice set.', read_safe: false, inputSchema: { type: 'object', properties: { scheme_version: { type: 'integer' }, category: { type: 'string' }, name: { type: 'string' }, steps: { type: 'array', items: { type: 'object' } }, fallback: { type: 'object' }, notPrimed: { type: 'object' }, enabled: { type: 'boolean' } }, required: ['scheme_version', 'category', 'name', 'steps'] } },
  { name: 'delete_scan_rule', description: 'Delete one scan rule (scheme version + single-digit category).', read_safe: false, inputSchema: { type: 'object', properties: { scheme_version: { type: 'integer' }, category: { type: 'string' } }, required: ['scheme_version', 'category'] } },

  // ── announcements.ts ────────────────────────────────────────────────────
  { name: 'publish_announcement', description: 'Publish a dashboard announcement — a banner every targeted user sees live and on their next load until it expires (default 24h) or they dismiss it. Only body (markdown) is required; title, layout, roles targeting, and expires_at are optional. Bodies broadcast to all authenticated subscribers — never include secrets.', read_safe: false, inputSchema: { type: 'object', properties: { body: { type: 'string' }, title: { type: 'string' }, layout: { type: 'string' }, roles: { type: 'array', items: { type: 'string' } }, expires_at: { type: 'string' } }, required: ['body'] } },
];
