import {
  Activity,
  AlertTriangle,
  Archive,
  Award,
  Barcode,
  Bell,
  Bot,
  Box,
  Boxes,
  Building2,
  Calendar,
  Camera,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cog,
  Cpu,
  Database,
  Download,
  Droplets,
  Factory,
  Fan,
  FileText,
  Flag,
  Flame,
  Gauge,
  Hammer,
  Heart,
  Image,
  Key,
  Layers,
  Leaf,
  LifeBuoy,
  ListChecks,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageSquare,
  Package,
  Palette,
  PenTool,
  Pill,
  Power,
  Printer,
  Receipt,
  Recycle,
  RefreshCw,
  Rocket,
  Route,
  Ruler,
  Scale,
  ScanBarcode,
  Scissors,
  Search,
  Send,
  Server,
  ShieldCheck,
  ShoppingCart,
  Snowflake,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  TestTube,
  Thermometer,
  Trash2,
  Truck,
  Upload,
  User,
  Users,
  Wand2,
  Warehouse,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { WORKFLOW_ICONS, isWorkflowIcon, type WorkflowIconName } from '../../../types/workflow-icons';

export { WORKFLOW_ICONS, isWorkflowIcon };
export type { WorkflowIconName };

// Static named imports keep the bundle to these glyphs alone; a namespace
// lookup would ship the whole library.
const GLYPHS: Record<WorkflowIconName, LucideIcon> = {
  Activity,
  AlertTriangle,
  Archive,
  Award,
  Barcode,
  Bell,
  Bot,
  Box,
  Boxes,
  Building2,
  Calendar,
  Camera,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cog,
  Cpu,
  Database,
  Download,
  Droplets,
  Factory,
  Fan,
  FileText,
  Flag,
  Flame,
  Gauge,
  Hammer,
  Heart,
  Image,
  Key,
  Layers,
  Leaf,
  LifeBuoy,
  ListChecks,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageSquare,
  Package,
  Palette,
  PenTool,
  Pill,
  Power,
  Printer,
  Receipt,
  Recycle,
  RefreshCw,
  Rocket,
  Route,
  Ruler,
  Scale,
  ScanBarcode,
  Scissors,
  Search,
  Send,
  Server,
  ShieldCheck,
  ShoppingCart,
  Snowflake,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  TestTube,
  Thermometer,
  Trash2,
  Truck,
  Upload,
  User,
  Users,
  Wand2,
  Warehouse,
  Wifi,
  Wrench,
  Zap,
};

/** Every curated icon, in the order the picker shows them. */
export const WORKFLOW_ICON_NAMES: readonly WorkflowIconName[] = Object.values(WORKFLOW_ICONS);

/** The constant key for a name (`Wrench` → `WRENCH`), for filtering by either. */
export const WORKFLOW_ICON_KEYS: Readonly<Record<WorkflowIconName, string>> = Object.fromEntries(
  Object.entries(WORKFLOW_ICONS).map(([key, name]) => [name, key]),
) as Record<WorkflowIconName, string>;

/** The glyph for a declared icon name; null for anything outside the curated set. */
export function workflowIconGlyph(name: string | null | undefined): LucideIcon | null {
  return isWorkflowIcon(name) ? GLYPHS[name] : null;
}

/** Names whose lucide name or constant key contains the query, case-insensitive. */
export function filterWorkflowIcons(query: string): WorkflowIconName[] {
  const q = query.trim().toLowerCase().replace(/[\s_-]+/g, '');
  if (!q) return [...WORKFLOW_ICON_NAMES];
  return WORKFLOW_ICON_NAMES.filter((name) =>
    name.toLowerCase().includes(q) || WORKFLOW_ICON_KEYS[name].toLowerCase().replace(/_/g, '').includes(q));
}
